trigger: none   

pool:
  name: Prod_infra

stages:
# ================= CI STAGE =================
- stage: CI
  displayName: Build & Scan
  jobs:
  - job: Build
    displayName: Build Job
    steps:

    # Install Node.js
    - task: NodeTool@0
      displayName: 'Install Node.js'
      inputs:
        versionSpec: '18.x'

    # Install npm dependencies
    - task: PowerShell@2
      displayName: 'npm install'
      inputs:
        targetType: 'inline'
        script: |
          npm install

    # Build project
    - task: PowerShell@2
      displayName: 'npm run build'
      inputs:
        targetType: 'inline'
        script: |
          npm run build

    # SonarQube Scan
    - task: PowerShell@2
      displayName: 'Run SonarQube Scanner'
      inputs:
        targetType: 'inline'
        script: |
          npm install -g sonar-scanner
          sonar-scanner `
            -Dsonar.projectKey=todoui-monolithic `
            -Dsonar.projectName=todoui-monolithic `
            -Dsonar.sources=. `
            -Dsonar.host.url=http://localhost:9000 `
            -Dsonar.login==$env:SONAR_TOKEN

    # Archive build
    - task: ArchiveFiles@2
      displayName: 'Archive build'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/build.zip'
        replaceExistingArchive: true

    # Publish artifact
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Artifact'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/build.zip'
        artifact: 'todo-ui'
        publishLocation: 'pipeline'

# ================= CD STAGE =================
- stage: Deploy
  displayName: Deploy to Dev VM
  dependsOn: CI
  jobs:
  - job: DeployJob
    displayName: Deploy Job
    steps:

    - task: DownloadPipelineArtifact@2
      displayName: 'Download Artifact'
      inputs:
        artifact: 'todo-ui'
        path: '$(System.DefaultWorkingDirectory)/build_artifact'
