trigger: none

pool:
  name: Prod_infra

steps:

# Install Node.js (this will also install npm)
- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '18.x'   # you can change version if needed

# Run npm install
- task: PowerShell@2
  displayName: 'npm install'
  inputs:
    targetType: 'inline'
    script: 'npm install'

# Run npm build
- task: PowerShell@2
  displayName: 'npm run build'
  inputs:
    targetType: 'inline'
    script: 'npm run build'


- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build/'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(System.DefaultWorkingDirectory)/build.zip'
    replaceExistingArchive: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/build.zip'
    artifact: 'todo-ui'
    publishLocation: 'pipeline'




